### PR TITLE
added github action CI

### PR DESCRIPTION
**Pull request by chcg**
See https://github.com/chcg/NPPTextFX2/actions/runs/4332380526.
What is the difference between Unicode Release and Release? 

Maybe you want to add this version to the built-in PluginAdmin, see also https://github.com/notepad-plus-plus/nppPluginList/issues/584. For that a zip package of the dll is needed.

### CODE REVIEW

**Comment by rainman74** [comment]
> Unicode Release

I only compile Unicode releases now. I have provided a zip file. What else needs to be done? Does the zip have to have a specific folder structure?

**Comment by chcg** [comment]
@rainman74 You need two zips one for x86 and one for x64. The dll needs to be in the toplevel folder of the zip. The version number of the dll is also relevant. In you case 1.2 as used in https://github.com/rainman74/NPPTextFX2/blob/main/SRC/NPPTextFX.rc. You could fork https://github.com/notepad-plus-plus/nppPluginList and add a new entry to https://github.com/notepad-plus-plus/nppPluginList/blob/master/src/pl.x64.json and https://github.com/notepad-plus-plus/nppPluginList/blob/master/src/pl.x86.json. 

If you like you could also create an arm64 version based on the x64 configuration.

The github action could be extended by https://github.com/softprops/action-gh-release to automatically create releases on tagging and add the dll as zip.

**Comment by rainman74** [comment]
> nppPluginList

Done, waiting for pending check.

**Comment by rainman74** [comment]
>

fixed, see https://github.com/notepad-plus-plus/nppPluginList/pull/590

**Pull request merged**
